/**
 * News API Endpoint
 * Returns current news sentiment, headlines, and trading restrictions.
 */

import fs from "fs";
import path from "path";

export default async function handler(req, res) {
  // Only allow GET
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    // Read the news state file generated by Python
    const newsPath = path.join(process.cwd(), "python_model", "news_state.json");
    
    // Check if news state file exists
    if (!fs.existsSync(newsPath)) {
      // Return default empty state if no news data yet
      return res.status(200).json({
        timestamp: new Date().toISOString(),
        can_trade: true,
        block_reason: null,
        sentiment: {
          score: 0,
          label: "NEUTRAL",
          bullish_count: 0,
          bearish_count: 0,
          neutral_count: 0
        },
        risk_multiplier: 1.0,
        high_impact_events: [],
        upcoming_events: [],
        headlines: [],
        available: false,
        message: "News module not initialized"
      });
    }

    // Read news state
    const newsData = fs.readFileSync(newsPath, "utf-8");
    const newsState = JSON.parse(newsData);

    // Add availability flag
    newsState.available = true;

    // Check freshness (warn if data is old)
    if (newsState.timestamp) {
      const stateTime = new Date(newsState.timestamp);
      const now = new Date();
      const minutesOld = (now - stateTime) / 1000 / 60;
      
      // Use news_age_minutes if available (more accurate)
      if (newsState.news_age_minutes !== undefined) {
        newsState.minutes_old = Math.round(newsState.news_age_minutes);
        if (newsState.news_age_minutes > 60) {
          newsState.stale = true;
        }
      } else if (minutesOld > 30) {
        newsState.stale = true;
        newsState.minutes_old = Math.round(minutesOld);
      }
    }

    res.status(200).json(newsState);

  } catch (err) {
    console.error("News API Error:", err);
    res.status(500).json({
      error: "Failed to fetch news data",
      message: err.message,
      available: false
    });
  }
}





