/**
 * API Route: /api/predict
 *
 * This route reads the prediction JSON file generated by the Python script
 * and returns it as JSON to the frontend.
 *
 * Works completely OFFLINE once latest_prediction.json is generated by Python.
 *
 * v2.0 Changes:
 * - Added validation of prediction structure
 * - Better error messages
 * - Handles new fields (htf_status, calibration_drift, etc.)
 *
 * Usage:
 * GET /api/predict
 * Returns: { generated_at, system_version, predictions: { ... } }
 */

import fs from "fs";
import path from "path";

export default function handler(req, res) {
  try {
    // Path to the prediction JSON file generated by Python
    const predictionPath = path.join(
      process.cwd(),
      "public",
      "latest_prediction.json"
    );

    // Check if file exists
    if (!fs.existsSync(predictionPath)) {
      return res.status(404).json({
        error: "Prediction file not found",
        message:
          'Please run "python predict.py" in the python_model directory to generate predictions.',
        file_path: predictionPath,
      });
    }

    // Read the prediction file
    const predictionData = fs.readFileSync(predictionPath, "utf-8");
    
    let prediction;
    try {
      prediction = JSON.parse(predictionData);
    } catch (parseError) {
      return res.status(500).json({
        error: "Invalid prediction file",
        message: "The prediction file is corrupted. Please regenerate predictions.",
        details: parseError.message
      });
    }

    // Validate prediction structure
    if (!prediction.predictions || typeof prediction.predictions !== 'object') {
      return res.status(500).json({
        error: "Invalid prediction format",
        message: "The prediction file has an invalid structure.",
      });
    }

    // Return prediction data with cache headers
    res.setHeader(
      "Cache-Control",
      "no-store, max-age=0"
    );
    res.setHeader("Content-Type", "application/json");
    res.status(200).json(prediction);
    
  } catch (error) {
    console.error("Error reading prediction file:", error);
    res.status(500).json({
      error: "Failed to read prediction",
      message: error.message,
    });
  }
}
